project:
  type: website
  output-dir: _site

website:
  title: "Anush Karampuri"
  description: "PhD Student in Bioinformatics & Genomics at Penn State University"

  navbar:
    left:
      - text: "CV"
        href: index.qmd
      - text: "Blog"
        href: posts.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/AnushKarampuri00
      - icon: linkedin
        href: https://www.linkedin.com/in/anush-karampuri-31bb33199/

  page-footer:
    center: "Â© 2026 Anush Karampuri"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header: _head.html
